server:
  port: 8003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: www.mynacos.com:8848
#        ip: www.mylocalhost.com
      config:
        enabled: false
  redis:
    host: www.myredis.com
    port: 6379
dubbo:
  protocol:
    name: dubbo
    port: 20884
#    host: 192.168.106.77 ip配置
  registry:
    #将dubbo服务挂在到Springcloud，本案例中就是读取nacos中的服务
    address: spring-cloud://localhost
  cloud:
    #订阅的服务
    subscribed-services: common-service
  consumer:
    #订阅的客户端不检查，dubbo在服务启动后，回去检查调用的Reference接口，检查失败，会导致启动不成功
    check: false
  application:
    name: consumer-service
  provider:
    #配置服务端超时时间
    timeout: 2000


security:
  oauth2:
    resource:
      id: service
      user-info-uri: http://localhost:8004/api/user/userInfo # 使用auth-server进行认证授权，
      prefer-token-info: false
